transportation/affairs/urls.py
from django.urls import path
from affairs import views

urlpatterns = [
    # Courier URLs
    path('courier/list', views.CourierListView, name='courier_list'),
    path('courier/create', views.CourierCreateView, name='courier_create'),
    path('courier/update/<int:id>', views.CourierUpdateView, name='courier_update'),
    path('courier/delete/<int:id>', views.CourierDeleteView, name='courier_delete'),

    # Transport URLs
    path('transport/list', views.TransportListView, name='transport_list'),
    path('transport/create', views.TransportCreateView, name='transport_create'),
    path('transport/update/<int:id>', views.TransportUpdateView, name='transport_update'),
    path('transport/delete/<int:id>', views.TransportDeleteView, name='transport_delete'),

    # Delivery URLs
    path('delivery/list', views.DeliveryListView, name='delivery_list'),
    path('delivery/create', views.DeliveryCreateView, name='delivery_create'),
    path('delivery/update/<int:id>', views.DeliveryUpdateView, name='delivery_update'),
    path('delivery/delete/<int:id>', views.DeliveryDeleteView, name='delivery_delete'),

    # Customer URLs
    path('customer/list', views.CustomerListView, name='customer_list'),
    path('customer/create', views.CustomerCreateView, name='customer_create'),
    path('customer/update/<int:id>', views.CustomerUpdateView, name='customer_update'),
    path('customer/delete/<int:id>', views.CustomerDeleteView, name='customer_delete'),

    # Main page
    path('index', views.MainPageView, name='main_page'),
]

transportation/transportation/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('affairs/', include('affairs.urls')),
    path('accounts/', include('accounts.urls')),
    path('captcha/',include('captcha.urls')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

transportation/affairs/models.py
from django.db import models

# Create your models here.

class TransportModel(models.Model):    
    departDate = models.DateField()
    arrivalDate = models.DateField()
    vehicleNo = models.CharField(max_length=100)
    courierId = models.ForeignKey("CourierModel",on_delete=models.PROTECT)
    source = models.CharField(max_length=100, null=True)
    destination = models.CharField(max_length=100, null= True)
    customerId = models.ForeignKey('CustomerModel',on_delete=models.PROTECT)

class CustomerModel (models.Model):
    name = models.CharField(max_length=100)
    surname = models.CharField(max_length=100)
    identityNo = models.IntegerField()
    address = models.CharField(max_length=500)

    def __str__(self):
        return 'Customer fullname is: {}{}'.format(self.name,self.surname)

class DeliveryModel(models.Model):
    dateTime = models.DateTimeField()
    isSuccessfull = models.BooleanField(default= False)
    courierId = models.ForeignKey("CourierModel",on_delete=models.PROTECT)

class CourierModel(models.Model):
    courierId = models.IntegerField(primary_key=True)
    cName = models.CharField(max_length=100)
    capacity = models.IntegerField()

    def __str__(self):
        return self.cName

transportation/affairs/forms.py
from .models import CourierModel, CustomerModel, TransportModel,DeliveryModel
from django import forms

class CourierForm(forms.ModelForm):
    class Meta:
        model = CourierModel
        fields = '__all__'

class CustomerForm(forms.ModelForm):
    class Meta:
        model = CustomerModel
        fields = '__all__'

class TransportForm(forms.ModelForm):
    class Meta:
        model = TransportModel
        fields = '__all__'


class DeliveryForm(forms.ModelForm):
    class Meta:
        model = DeliveryModel
        fields = '__all__'

transportation/affairs/views.py
from django.shortcuts import render
from .models import CourierModel, TransportModel, DeliveryModel, CustomerModel
from .forms import TransportForm, DeliveryForm, CustomerForm, CourierForm
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from affairs import views
from django.contrib.auth.decorators import login_required

# Create your views here.
@login_required
def CourierListView(request):
    couriers = CourierModel.objects.all()

    context = {
        'courier': couriers
    }

    return render(request,'affairs/CourierList.html',context)

@login_required
def CourierCreateView(request):
    if request.method == 'POST':
        courierForm = CourierForm(request.POST)
        if courierForm.is_valid:
            courierForm.save()
            return HttpResponseRedirect(reverse(views.CourierListView))
    else:
        courierForm = CourierForm()

    context = {
        'coForm': courierForm
    }

    return render(request,'affairs/CourierCreate.html',context)

@login_required
def CourierUpdateView(request,id):
    cInstance = CourierModel.objects.get(pk=id)
    if request.method == 'POST':
        courierForm = CourierForm(request.POST,instance=cInstance)
        if courierForm.is_valid:
            courierForm.save()
            return HttpResponseRedirect(reverse(views.CourierListView))
    else:
        courierForm = CourierForm(instance=cInstance)

    context = {
        'coForm': courierForm
    }

    return render(request,'affairs/CourierUpdate.html',context)

@login_required
def CourierDeleteView(request,id):
    cInstance = CourierModel.objects.get(pk=id)
    cInstance.delete()
    return HttpResponseRedirect(reverse(views.CourierListView))
    

def TransportListView(request):
    transports = TransportModel.objects.all()

    context = {
        'transports': transports
    }
    return render(request,'affairs/TransportList.html',context)

@login_required
def TransportCreateView(request):
    if request.method == 'POST':
        transportForm = TransportForm(request.POST)
        if transportForm.is_valid:
            transportForm.save()
            return HttpResponseRedirect(reverse(views.TransportListView))
    else:
        transportForm = TransportForm()

    context = {
        'tForm': transportForm
    }

    return render(request,'affairs/TransportCreate.html',context)

@login_required
def TransportUpdateView(request,id):
    tInstance = TransportModel.objects.get(pk=id)
    if request.method == 'POST':
        transportForm = TransportForm(request.POST,instance=tInstance)
        if transportForm.is_valid:
            transportForm.save()
            return HttpResponseRedirect(reverse(views.TransportListView))
    else:
        transportForm = TransportForm(instance=tInstance)

    context = {
        'tForm': transportForm
    }

    return render(request,'affairs/TransportUpdate.html',context)

@login_required
def TransportDeleteView(request,id):
    tInstance = TransportModel.objects.get(pk=id)
    tInstance.delete()
    return HttpResponseRedirect(reverse(views.TransportListView))



def DeliveryListView(request):
    deliveries = DeliveryModel.objects.all()

    context = {
        'deliveries': deliveries
    }
    return render(request,'affairs/DeliveryList.html',context)

@login_required
def DeliveryCreateView(request):
    if request.method == 'POST':
        deliveryForm = DeliveryForm(request.POST)
        if deliveryForm.is_valid:
            deliveryForm.save()
            return HttpResponseRedirect(reverse(views.DeliveryListView))
    else:
        deliveryForm = DeliveryForm()

    context = {
        'dForm': deliveryForm
    }

    return render(request,'affairs/DeliveryCreate.html',context)


@login_required
def DeliveryUpdateView(request,id):
    dInstance = DeliveryModel.objects.get(pk=id)
    if request.method == 'POST':
        deliveryForm = DeliveryForm(request.POST,instance=dInstance)
        if deliveryForm.is_valid:
            deliveryForm.save()
            return HttpResponseRedirect(reverse(views.DeliveryListView))
    else:
        deliveryForm = DeliveryForm(instance=dInstance)

    context = {
        'dForm': deliveryForm
    }

    return render(request,'affairs/DeliveryUpdate.html',context)

@login_required
def DeliveryDeleteView(request,id):
    dInstance = DeliveryModel.objects.get(pk=id)
    dInstance.delete()
    return HttpResponseRedirect(reverse(views.DeliveryListView))

@login_required
def CustomerListView(request):
    customers = CustomerModel.objects.all()

    context = {
        'customers': customers
    }
    return render(request,'affairs/CustomerList.html',context)


def CustomerCreateView(request):
    if request.method == 'POST':
        customerForm = CustomerForm(request.POST)
        if customerForm.is_valid:
            customerForm.save()
            return HttpResponseRedirect(reverse(views.CustomerListView))
    else:
        customerForm = CustomerForm()

    context = {
        'cForm': customerForm
    }

    return render(request,'affairs/CustomerCreate.html',context)

@login_required
def CustomerUpdateView(request,id):
    cInstance = CustomerModel.objects.get(pk=id)
    if request.method == 'POST':
        customerForm = CustomerForm(request.POST,instance=cInstance)
        if customerForm.is_valid:
            customerForm.save()
            return HttpResponseRedirect(reverse(views.CustomerListView))
    else:
        customerForm = CustomerForm(instance=cInstance)

    context = {
        'cForm': customerForm
    }

    return render(request,'affairs/CustomerUpdate.html',context)

@login_required
def CustomerDeleteView(request,id): 
    try:   
        cInstance = CustomerModel.objects.get(pk=id)
        cInstance.delete()
        return HttpResponseRedirect(reverse(views.CustomerListView))
    except:
        return HttpResponse('Integrity Problem')
        


def MainPageView(request):
    return render(request,'affairs/index.html',{})

transportation/affairs/templates/affairs/CourierCreate.html
{% extends "affairs/layout.html" %}
{% load static %}

{% block titlepage %}
  Insert New Courier
{% endblock %}

{% block mainContent %}
<div class="container mt-4">
  <form method="POST" enctype="multipart/form-data" class="p-4 border rounded shadow-sm bg-light">
    {% csrf_token %}
    <div class="row mb-3">
      <div class="col-md-6">
        <div class="mb-3">
          <label class="form-label fw-bold">Courier ID</label>
          {{ coForm.courierId }}
        </div>
        <div class="mb-3">
          <label class="form-label fw-bold">Courier Name</label>
          {{ coForm.cName }}
        </div>
        <div class="mb-3">
          <label class="form-label fw-bold">Capacity</label>
          {{ coForm.capacity }}
        </div>
        <button type="submit" class="btn btn-success">Create</button>
      </div>
    </div>
  </form>
</div>
{% endblock %}

transportation/affairs/templates/affairs/CourierList.html
{% extends "affairs/layout.html" %}
{% load static %}

{% block titlepage %}
  Courier List
{% endblock %}

{% block mainContent %}
<div class="container mt-3">
  <div class="d-flex justify-content-between align-items-center mb-3">
    <h4 class="fw-bold">Courier Records</h4>
    <a href="{% url 'courier_create' %}" class="btn btn-primary">Insert New Courier</a>
  </div>

  <div class="row g-3">
    {% for co in courier %}
      <div class="col-md-4">
        <div class="card shadow-sm h-100">
          <div class="card-body">
            <h5 class="card-title text-success">Courier ID: {{ co.courierId }}</h5>
            <p class="card-text">Name: {{ co.cName }}</p>
            <p class="card-text">Capacity: {{ co.capacity }}</p>
            <div class="d-flex justify-content-between">
              <a href="{% url 'courier_update' co.courierId %}" class="btn btn-success btn-sm">Update</a>
              <a href="{% url 'courier_delete' co.courierId %}" class="btn btn-danger btn-sm" onclick="return warning()">Delete</a>
            </div>
          </div>
        </div>
      </div>
    {% empty %}
      <p class="text-muted">No couriers found.</p>
    {% endfor %}
  </div>
</div>
{% endblock %}

transportation/affairs/templates/affairs/CourierUpdate.html
{% extends "affairs/layout.html" %}
{% load static %}

{% block titlepage %}
  Update Courier
{% endblock %}

{% block mainContent %}
<div class="container mt-4">
  <form method="POST" enctype="multipart/form-data" class="p-4 border rounded shadow-sm bg-light">
    {% csrf_token %}
    <div class="row">
      <div class="col-md-6">
        <div class="mb-3">
          <label class="form-label fw-bold">Courier ID</label>
          {{ coForm.courierId }}
        </div>
        <div class="mb-3">
          <label class="form-label fw-bold">Courier Name</label>
          {{ coForm.cName }}
        </div>
        <div class="mb-3">
          <label class="form-label fw-bold">Capacity</label>
          {{ coForm.capacity }}
        </div>
        <button type="submit" class="btn btn-success">Update</button>
      </div>
    </div>
  </form>
</div>
{% endblock %}

transportation/affairs/templates/affairs/CustomerCreate.html
{% extends "affairs/layout.html" %}
{% block titlepage %}
  Register New Customer
{% endblock %}

{% block mainContent %}
<div class="container mt-4">
  <form method="POST" enctype="multipart/form-data" class="p-4 border rounded shadow-sm bg-light">
    {% csrf_token %}
    <div class="row">
      <div class="col-md-6">

        <div class="mb-3">
          <label class="form-label fw-bold">Name</label>
          {{ cForm.name }}
        </div>

        <div class="mb-3">
          <label class="form-label fw-bold">Surname</label>
          {{ cForm.surname }}
        </div>

        <div class="mb-3">
          <label class="form-label fw-bold">Identity Number</label>
          {{ cForm.identityNo }}
        </div>

        <div class="mb-3">
          <label class="form-label fw-bold">Address</label>
          {{ cForm.address }}
        </div>

        <button type="submit" class="btn btn-success">Create</button>
      </div>
    </div>
  </form>
</div>
{% endblock %}

transportation/affairs/templates/affairs/CustomerList.html
{% extends "affairs/layout.html" %}
{% load static %}

{% block titlepage %}
  Customer List
{% endblock %}

{% block mainContent %}
<div class="container mt-3">
  <div class="row g-4">
    {% for cl in customers %}
      <div class="col-md-4">
        <div class="card shadow-sm h-100">
          <div class="card-body">
            <h5 class="card-title text-primary">{{ cl.name }} {{ cl.surname }}</h5>
            <p class="card-text"><strong>Identity No:</strong> {{ cl.identityNo }}</p>
            <p class="card-text"><strong>Address:</strong> {{ cl.address }}</p>
            <div class="d-flex justify-content-between">
              <a href="{% url 'customer_update' cl.id %}" class="btn btn-success btn-sm">Update</a>
              <a href="{% url 'customer_delete' cl.id %}" class="btn btn-danger btn-sm" onclick="return warning()">Delete</a>
            </div>
          </div>
        </div>
      </div>
    {% empty %}
      <p class="text-muted">No customers found.</p>
    {% endfor %}
  </div>
</div>
{% endblock %}

transportation/affairs/templates/affairs/CustomerUpdate.html
{% extends "affairs/layout.html" %}
{% load static %}

{% block titlepage %}
  Update Customer
{% endblock %}

{% block mainContent %}
<div class="container mt-4">
  <form method="POST" enctype="multipart/form-data" class="p-4 border rounded shadow-sm bg-light">
    {% csrf_token %}
    <div class="row">
      <div class="col-md-6">

        <div class="mb-3">
          <label class="form-label fw-bold">Name</label>
          {{ cForm.name }}
        </div>

        <div class="mb-3">
          <label class="form-label fw-bold">Surname</label>
          {{ cForm.surname }}
        </div>

        <div class="mb-3">
          <label class="form-label fw-bold">Identity Number</label>
          {{ cForm.identityNo }}
        </div>

        <div class="mb-3">
          <label class="form-label fw-bold">Address</label>
          {{ cForm.address }}
        </div>

        <button type="submit" class="btn btn-success">Update</button>
      </div>
    </div>
  </form>
</div>
{% endblock %}

transportation/affairs/templates/affairs/DeliveryCreate.html
{% extends "affairs/layout.html" %}
{% load static %}

{% block titlepage %}
  Insert New Delivery
{% endblock %}

{% block mainContent %}
<div class="container mt-4">
  <form method="POST" enctype="multipart/form-data" class="p-4 border rounded shadow-sm bg-light">
    {% csrf_token %}
    <div class="row">
      <div class="col-md-6">

        <div class="mb-3">
          <label class="form-label fw-bold">Date & Time</label>
          {{ dForm.dateTime }}
        </div>

        <div class="mb-3">
          <label class="form-label fw-bold">Status of Delivery</label>
          {{ dForm.isSuccessfull }}
        </div>

        <div class="mb-3">
          <label class="form-label fw-bold">Courier</label>
          {{ dForm.courierId }}
        </div>

        <button type="submit" class="btn btn-success">Create</button>
      </div>
    </div>
  </form>
</div>
{% endblock %}

transportation/affairs/templates/affairs/DeliveryList.html
{% extends "affairs/layout.html" %}

{% block titlepage %} Delivery List {% endblock %}

{% block mainContent %}
<div class="container mt-3">
  <div class="mb-3">
    <a href="{% url 'delivery_create' %}" class="btn btn-primary">Insert new delivery</a>
  </div>
  
  <div class="row g-4">
    {% for dl in deliveries %}
      <div class="col-md-4">
        <div class="card shadow-sm h-100">
          <div class="card-body">
            <h5 class="card-title">Delivery ID: {{ dl.id }}</h5>
            <p class="card-text"><strong>Date & Time:</strong> {{ dl.dateTime }}</p>
            <p class="card-text"><strong>Status:</strong> {{ dl.isSuccessfull|yesno:"Successful,Unsuccessful" }}</p>
            <p class="card-text"><strong>Courier ID:</strong> {{ dl.courierId }}</p>
            <div class="d-flex justify-content-between">
              <a href="{% url 'delivery_update' dl.id %}" class="btn btn-success btn-sm">Update</a>
              <a href="{% url 'delivery_delete' dl.id %}" class="btn btn-danger btn-sm" onclick="return warning()">Delete</a>
            </div>
          </div>
        </div>
      </div>
    {% empty %}
      <p class="text-muted">No deliveries found.</p>
    {% endfor %}
  </div>
</div>
{% endblock %}

transportation/affairs/templates/affairs/DeliveryUpdate.html
{% extends "affairs/layout.html" %}
{% load static %}

{% block titlepage %} Update Delivery {% endblock %}

{% block mainContent %}
<div class="container mt-4">
  <form method="POST" enctype="multipart/form-data" class="p-4 border rounded shadow-sm bg-light">
    {% csrf_token %}
    <div class="row">
      <div class="col-md-6">

        <div class="mb-3">
          <label class="form-label fw-bold">Date & Time</label>
          {{ dForm.dateTime }}
        </div>

        <div class="mb-3">
          <label class="form-label fw-bold">Status of Delivery</label>
          {{ dForm.isSuccessfull }}
        </div>

        <div class="mb-3">
          <label class="form-label fw-bold">Courier ID</label>
          {{ dForm.courierId }}
        </div>

        <button type="submit" class="btn btn-success">Update</button>
      </div>
    </div>
  </form>
</div>
{% endblock %}

transportation/affairs/templates/affairs/TransportCreate.html
{% extends "affairs/layout.html" %}
{% load static %}

{% block titlepage %} Insert New Transport {% endblock %}

{% block mainContent %}
<div class="container mt-4">
  <form method="POST" enctype="multipart/form-data" class="p-4 border rounded shadow-sm bg-light">
    {% csrf_token %}
    <div class="row">
      <div class="col-md-6">

        <div class="mb-3">
          <label for="vehicleNo" class="form-label fw-bold">Vehicle Number</label>
          {{ tForm.vehicleNo }}
        </div>

        <div class="mb-3">
          <label for="departDate" class="form-label fw-bold">Departure Date</label>
          {{ tForm.departDate }}
        </div>

        <div class="mb-3">
          <label for="arrivalDate" class="form-label fw-bold">Arrival Date</label>
          {{ tForm.arrivalDate }}
        </div>

        <div class="mb-3">
          <label for="courierId" class="form-label fw-bold">Courier ID</label>
          {{ tForm.courierId }}
        </div>

        <div class="mb-3">
          <label for="source" class="form-label fw-bold">Source</label>
          {{ tForm.source }}
        </div>

        <div class="mb-3">
          <label for="destination" class="form-label fw-bold">Destination</label>
          {{ tForm.destination }}
        </div>

        <div class="mb-3">
          <label for="customerId" class="form-label fw-bold">Customer ID</label>
          {{ tForm.customerId }}
        </div>

        <button type="submit" class="btn btn-success">Create</button>

      </div>
    </div>
  </form>
</div>
{% endblock %}

transportation/affairs/templates/affairs/TransportList.html
{% extends "affairs/layout.html" %}
{% block titlepage %} Transport List {% endblock %}
{% block mainContent %}
<div class="mb-3">
  <a href="create" class="btn btn-primary">Insert new transport</a>
</div>

<div class="row">
  {% for tr in transports %}
    <div class="col-md-4 mb-4">
      <div class="card h-100 shadow-sm">
        <div class="card-body">
          <div class="d-flex justify-content-between mb-2">
            <a href="update/{{ tr.id }}" class="btn btn-sm btn-success">Update</a>
            <a href="delete/{{ tr.id }}" class="btn btn-sm btn-danger" onclick="return warning()">Delete</a>
          </div>
          <p><strong>Vehicle Number:</strong> {{ tr.vehicleNo }}</p>
          <p><strong>Departure Date:</strong> {{ tr.departDate }}</p>
          <p><strong>Arrival Date:</strong> {{ tr.arrivalDate }}</p>
          <p><strong>Courier ID:</strong> {{ tr.courierId }}</p>
          <p><strong>Source:</strong> {{ tr.source }}</p>
          <p><strong>Destination:</strong> {{ tr.destination }}</p>
          <p><strong>Customer ID:</strong> {{ tr.customerId }}</p>
        </div>
      </div>
    </div>
  {% endfor %}
</div>
{% endblock %}

transportation/affairs/templates/affairs/TransportUpdate.html
{% extends "affairs/layout.html" %}
{% block titlepage %} Update Transport {% endblock %}
{% block mainContent %}
<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="mainborder p-3">
        <div class="row">
            <div class="col-md-6">
                <div class="mb-3">
                    <label for="id_vehicleNo" class="form-label">Vehicle Number</label>
                    {{ tForm.vehicleNo }}
                </div>
                <div class="mb-3">
                    <label for="id_departDate" class="form-label">Departure Date</label>
                    {{ tForm.departDate }}
                </div>
                <div class="mb-3">
                    <label for="id_arrivalDate" class="form-label">Arrival Date</label>
                    {{ tForm.arrivalDate }}
                </div>
                <div class="mb-3">
                    <label for="id_courierId" class="form-label">Courier ID</label>
                    {{ tForm.courierId }}
                </div>
                <div class="mb-3">
                    <label for="id_source" class="form-label">Source</label>
                    {{ tForm.source }}
                </div>
                <div class="mb-3">
                    <label for="id_destination" class="form-label">Destination</label>
                    {{ tForm.destination }}
                </div>
                <div class="mb-3">
                    <label for="id_customerId" class="form-label">Customer ID</label>
                    {{ tForm.customerId }}
                </div>
                <button type="submit" class="btn btn-success">Update</button>
            </div>
        </div>
    </div>
</form>
{% endblock %}

transportation/affairs/templates/affairs/index.html
{% extends "affairs/layout.html" %}
{% load static %}

{% block titlepage %} Transportation Management System {% endblock %}

{% block mainContent %}
<div class="container mt-4">
  <div class="row justify-content-center">
    <div class="col-12">
      <img 
        src="{% static 'affairs/images/transportation.jpg' %}" 
        alt="Transportation" 
        class="img-fluid rounded shadow-sm" />
    </div>
  </div>
</div>
{% endblock %}

transportation/affairs/templates/affairs/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>Transportation Management System</title>

	<!-- Styles -->
	<link rel="stylesheet" href="{% static 'affairs/css/bootstrap.css' %}" />
	<link rel="stylesheet" href="{% static 'affairs/css/fontawesome.css' %}" />
	<link rel="stylesheet" href="{% static 'affairs/css/style.css' %}" />

	<!-- Scripts -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

	<script>
		$(function () {
			// CAPTCHA Refresh
			$('.captcha-refresh').click(function () {
				const $form = $(this).closest('form');
				const url = `${location.protocol}//${window.location.hostname}${location.port ? ':' + location.port : ''}/captcha/refresh/`;

				$.getJSON(url, {}, function (json) {
					$form.find('input[name="captcha_0"]').val(json.key);
					$form.find('img.captcha').attr('src', json.image_url);
				});
				return false;
			});
		});

		function warning() {
			return confirm("Are you sure?!"); 
		}
	</script>

	<style>
		.dropdown:hover .dropdown-menu {
			display: block;
		}
	</style>
</head>

<body>
	<nav class="navbar navbar-expand-lg navbar-dark bg-success">
		<div class="container-fluid">
			<a class="navbar-brand fw-bold fst-italic" href="#">Transportation Site</a>
			<button
				class="navbar-toggler"
				type="button"
				data-bs-toggle="collapse"
				data-bs-target="#navbarNav"
				aria-controls="navbarNav"
				aria-expanded="false"
				aria-label="Toggle navigation"
			>
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="navbarNav">
				<ul class="navbar-nav me-auto mb-2 mb-lg-0">
					<li class="nav-item">
						<a class="nav-link {% if request.path == '/affairs/index' %}active{% endif %}" href="/affairs/index">Home</a>
					</li>
					<li class="nav-item">
						<a class="nav-link {% if request.path == '/affairs/customer/create' %}active{% endif %}" href="/affairs/customer/create">Customer Registration</a>
					</li>
					<li class="nav-item">
						<a class="nav-link {% if request.path == '/affairs/delivery/list' %}active{% endif %}" href="/affairs/delivery/list">Delivery List</a>
					</li>
					<li class="nav-item">
						<a class="nav-link {% if request.path == '/affairs/transport/list' %}active{% endif %}" href="/affairs/transport/list">Transport List</a>
					</li>

					{% if user.is_authenticated %}
						<li class="nav-item dropdown">
							<a
								class="nav-link dropdown-toggle"
								href="#"
								id="adminDropdown"
								role="button"
								data-bs-toggle="dropdown"
								aria-expanded="false"
							>
								Administration
							</a>
							<ul class="dropdown-menu" aria-labelledby="adminDropdown">
								<li><a class="dropdown-item" href="/affairs/customer/list">Customer List</a></li>
								<li><a class="dropdown-item" href="/affairs/courier/list">Courier List</a></li>
							</ul>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="/accounts/profile">Profile</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-danger" href="/accounts/logout">Logout</a>
						</li>
					{% else %}
						<li class="nav-item">
							<a class="nav-link text-danger" href="/accounts/profileRegister">Register</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-light" href="/accounts/login">Login</a>
						</li>
					{% endif %}
				</ul>
			</div>
		</div>
	</nav>

	<div class="container mt-4">
		<h2 class="text-center mb-4">{% block titlepage %}{% endblock %}</h2>
		{% block mainContent %}{% endblock %}
	</div>

	<!-- Bootstrap Bundle (includes Popper) -->
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>